### PR TITLE
Add responsiveness

### PR DESCRIPTION
**Pull request by d4rky-pl**
This PR makes entire website responsive.

It's not perfect yet (for example map is covered with the little guy on rocket) but @voter101 said something about more proper redesign so it's mostly so the website is usable via phone this weekend.

### CODE REVIEW

**Comment by pawelpacana** [comment]
https://deploy-preview-4--wrocloverb-2018.netlify.com

**Comment by pawelpacana** [comment]
Would merge :)

Something happened to agenda background though:
zrzut ekranu 2018-03-13 o 17 52 50

**Comment by d4rky-pl** [comment]
@pawelpacana what browser is this?

**Comment by d4rky-pl** [comment]
@pawelpacana oh, right, The Broken One. I will figure out a workaround and ping you again ;)

**Pull request merged**
